### ISSUE TITLE
Add documentation on M1 installation issues

### ISSUE THREAD

**Issue by richford** [yeatmanlab/AFQ-Insight#129]
`tables` has trouble installing on M1 macs. The workaround it to do the following before installing AFQ-Insight
```
pip install cython
brew install hdf5
brew install c-blosc
export HDF5_DIR=/opt/homebrew/opt/hdf5 
export BLOSC_DIR=/opt/homebrew/opt/c-blosc
pip install tables
```

We should add this to the documentation.

**Comment by arokem** [comment]
Closed through https://github.com/tractometry/AFQ-Insight/pull/14
